make status nullable
elifesciences/patterns-php pull request #949
Opened 2023-02-09 12:06 UTC by smoqadam

2023-02-10 10:00 UTC, nlisgo approved these changes
test needed

2023-02-10 10:00 UTC, nlisgo commented on src/ViewModel/ContentAside.php
> +        ContentAsideStatus $status = null,
Please can we add a test.

2023-02-10 11:13 UTC, smoqadam commented on src/ViewModel/ContentAside.php
> +        ContentAsideStatus $status = null,
@nlisgo Tests added

2023-02-14 09:35 UTC, nlisgo requested changes

2023-02-14 09:35 UTC, nlisgo commented on tests/src/ViewModel/ContentAsideTest.php
> +        $this->assertNull($contentAside['status']);
We have used the variables `$with` and `$without` fairly consistently throughout the tests in this library. 

See: https://github.com/elifesciences/patterns-php/blob/0b2f593568ec06abc4958cef10fdddad57f2ff68/tests/src/ViewModel/AboutProfileTest.php#L73-L82

2023-02-16 18:21 UTC, nlisgo approved these changes

2023-02-16 18:25 UTC, merged